language: objective-c
osx_image: xcode9.4
xcode_workspace: xikolo-ios.xcworkspace
cache: cocoapods

env:
  - CHECK_LOCALIZATION=1
  - LINT=1
  - BUILD=1 SCHEME="openHPI-iOS" SDK="iphonesimulator"
  - TEST=1 SCHEME="openHPI-iOS"
  - TEST=1 SCHEME="Common"

install:
  - bundle install --without documentation
  - bundle exec pod repo update > /dev/null
  - bundle exec pod install

script:
  - set -o pipefail
  - if [ "$BUILD" == 1 ]; then xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $SCHEME -sdk $SDK build | xcpretty; fi
  - if [ "$TEST" == 1 ]; then bundle exec fastlane scheme:$SCHEME; fi
  - if [ "$CHECK_LOCALIZATION" == 1 ]; then bundle exec fastlane localize; git status --porcelain; git diff --quiet head Common iOS || travis_terminate 1; fi
  - if [ "$LINT" == 1 ]; then bundle exec danger --verbose; fi
